// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyr-YOXSnIJx5BNZYKTJEfnmgisBszoYo',
    appId: '1:908528538420:web:dbd2ef3630c518fa2a0b61',
    messagingSenderId: '908528538420',
    projectId: 'diabetes-app-81f7d',
    authDomain: 'diabetes-app-81f7d.firebaseapp.com',
    storageBucket: 'diabetes-app-81f7d.firebasestorage.app',
    measurementId: 'G-T77DY8ECL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcZo4bmKzvn9_VZAE99aMI1_K3edTz78',
    appId: '1:908528538420:android:937113f50bcc8f212a0b61',
    messagingSenderId: '908528538420',
    projectId: 'diabetes-app-81f7d',
    storageBucket: 'diabetes-app-81f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHylHIUeQ7SA7oXeNiJxQDaWv8Dn2n-P0',
    appId: '1:908528538420:ios:64cd79c8b8ed8de42a0b61',
    messagingSenderId: '908528538420',
    projectId: 'diabetes-app-81f7d',
    storageBucket: 'diabetes-app-81f7d.firebasestorage.app',
    iosBundleId: 'com.example.diabetesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHylHIUeQ7SA7oXeNiJxQDaWv8Dn2n-P0',
    appId: '1:908528538420:ios:64cd79c8b8ed8de42a0b61',
    messagingSenderId: '908528538420',
    projectId: 'diabetes-app-81f7d',
    storageBucket: 'diabetes-app-81f7d.firebasestorage.app',
    iosBundleId: 'com.example.diabetesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyr-YOXSnIJx5BNZYKTJEfnmgisBszoYo',
    appId: '1:908528538420:web:b8f81bc5b6e28b8a2a0b61',
    messagingSenderId: '908528538420',
    projectId: 'diabetes-app-81f7d',
    authDomain: 'diabetes-app-81f7d.firebaseapp.com',
    storageBucket: 'diabetes-app-81f7d.firebasestorage.app',
    measurementId: 'G-MZNH85447C',
  );
}
